name: Docker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        base:
        - bash:alpine3.18
        platforms:
        - linux/amd64 linux/arm64
        version:
        - "1.0.0"

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      id: config
      run: |-
        NPROC=$(nproc)

        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_ENV
        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_OUTPUT

        echo "repo-owner=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
        echo "repo-name=${GITHUB_REPOSITORY#*/docker-}" >> $GITHUB_OUTPUT

    - name: Setup - QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2.2.0
      with:
        platforms: ${{ matrix.platforms || env.PLATFORMS || 'all' }}

    - name: Setup - Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup - Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |-
          ${{ steps.config.outputs.repo-owner }}/${{ steps.config.outputs.repo-name }}
          ghcr.io/${{ steps.config.outputs.repo-owner }}/${{ steps.config.outputs.repo-name }}
        flavor: |-
          latest=${{ !!matrix.latest }}
        tags: |-
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.version }}

    - name: Build
      uses: docker/build-push-action@v4
      id: build
      with:
        context: .
        build-args: |
          base=${{ matrix.base }}
          version=${{ matrix.version }}
        push: true
        platforms: ${{ steps.qemu.outputs.platforms }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
